name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync Files to VPS
        uses: Sayemahamed/DeployStream/.github/actions/fileSync@main 
        with:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_IPADDRESS: ${{ secrets.SSH_IPADDRESS }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          LOCAL_PATH: ${{ secrets.LOCAL_PATH }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}